# Generated by Django 4.2.2 on 2023-06-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(verbose_name="入学时间"),
        ),
    ]
