# Generated by Django 4.2.2 on 2023-06-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_userinfo_create_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=11, verbose_name="卡号")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "学生卡"), (2, "教师卡"), (3, "职工卡"), (4, "临时卡")],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "未激活"), (2, "已激活")], default=1, verbose_name="状态"
                    ),
                ),
            ],
        ),
    ]
